### ISSUE TITLE
Why not make a GitHub site?

### ISSUE THREAD

**Issue by aelias36** [rpi-graduate-council/grad-wiki#1]
Since files are already in Markdown, GitHub can host the wiki as a website. Let me know if you want help with this.

https://pages.github.com/
https://www.markdownguide.org/tools/github-pages/
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll

**Comment by diyanko** [comment]
Yes, this is already being considered and is relatively important for everyone to have an easy way to view the info in any device through a site.

Now we have a couple of options here.
Github Pages is a good option which is free and relatively customizable. I am just a little worried about the work that might be needed in the long term to keep it up and running and how complex it may be for people who are not well versed with it. Another option is [Obsidian Publish](https://obsidian.md/publish). Even though this is paid (that is something that the Grad Council can take care of), it seems to be a simpler out-of-the-box experience and looks prettier with less work, it seems.

We need to think about all the options and make a wise decision for the long term.

**Comment by lutsevai** [comment]
As I remember I decided not to use GitHub Pages due to ~~versioning~~ problems with dynamic links. As @diyanko mentioned, our current plan is to go for Obsidian Publish. Regardless, it would be great to have your input - can you join the Grad Council meeting this Friday 3pm @ UNION 3418?

**Comment by lutsevai** [comment]
Quoting Inwon Kang: "Github pages does not support dynamic urls, so homepage.com/ will work, but nested pages such as homepage/page/page1 may not work with modern frameworks which require a router from the server. unless you make everything standalone html files. even then it may not work unless the user starts the navigation from a homepage"

**Comment by inwonakng** [comment]
To elaborate -- 

This will work with something like jekyll or anything else that bundles pages into pre-defined *standalone* html files (e.g. [http://jekyll.github.io/example/](http://jekyll.github.io/example/)), but not with a framework that requires a router to kick in before the user sees a page. This process could be automated (i.e. converting obsidian directory format to jekyll for deployment), but may require a custom script instead of popular frameworks (many of which require a router-like setup which will not work on github pages).

Pros to static sites:
- simple
- allows for static links (ending with html)
- People don't need to touch the repo

Cons:
- Limited functionality (not really an issue since it's just a docs page)
- Someone needs to maintain it (extra work on top of just having the files)

And versioning should not be an issue since that is the point of using git. If so desired we can have "release versions" to keep revisions grouped, but I don't think there is much of a point in doing that.

**Comment by lutsevai** [comment]
Closing as being resolved.
